[package]
name = "leap-cli"
version = "0.1.3"
edition = "2021"
authors = ["Roman Kudryavtsev <rskbox@gmail.com>"]
license = "MIT"
description = "Leap language command line tool"
repository = "https://github.com/rsk700/leap-cli"
readme = "README.md"

[dependencies]
leap-lang = "0.1"
clap = "2.33"