[package]
name = "leap-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leap-lang = { path = "../leap-lang", version = "0.1" }
clap = "2.33"